# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6fb497dd99c2a3a6e6f84ffb7df8b851de5b112c6c3657f3e3b9956d9aa262e984b3331bd5727bab596ba382b6647464b9b3b6ec2f65ff0c0b78245961dc803

test:
  secret_key_base: 8ef181aa3f84fb97bf3585877aef4bfee8757c9fa0e291c68a55d07d8d1b07c75e99c39ace4386175855a16561d93519b478931f5fac495634e1b6e8057ccca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
